### PR TITLE
Updated FreeBSD modules for 14.0Release.

### PR DESCRIPTION
**Pull request by DrBassman**
Fixes so that FreeBSD 14.0 Release Images can boot from Ventoy.  Fixes Issue #2636.

### CODE REVIEW

**Comment by ventoy** [comment]
I have updated in latest release.

**Comment by rwgbsd** [comment]
I just tried the 1.0.98 and still FreeBSD 14 fails to boot with a cant find cdrom error

**Comment by DrBassman** [comment]
I cannot replicate the error.

Furthermore, I can verify that the "just released" FreeBSD **14.1**Release also is working with 1.0.98.

**Comment by rwgbsd** [comment]
Perhaps then it is something different I have done while creating my ventoy stick.  I DO override the type of stick to GPT, and the file system type for the ISO partition to ntfs.  I'll create a stick that uses all the defaults and see what happens.
My current stick with the above mentioned overrides fails FreeBSD 14, 14.1, but works fine for debian 12.5.

**Comment by rwgbsd** [comment]
Using the default MBR and ExFAT settings does infact work, I am now apply one change at a time to find out when it breaks.
GPT and ExFAT works.  MBR and NTFS works.  GPT and NTFS works.   Hummm... I did flip the bios mode to legacy during this testing, which still allows one to do a UEFI boot by overide.  I have flipped it back to UEFI and it is still working.  For now chalk this one up to a stray unknown, if I can get it doing it again I'll try to narrow the conditions.

**Pull request closed without merging**
