### PR TITLE
add grub/menu hi.json (hindi)

### PR DESCRIPTION
**Pull request by wiz64**
Note* - took language-code reference from : https://wiki.freepascal.org/Language_Codes

### CODE REVIEW

**Comment by ventoy** [comment]
I changed the hotkey in the latest commit, so please update the json file. (You can refer the latest en_US.json)

**Comment by wiz64** [comment]
A bit confused about the naming standard ?
hi.json is fine or it needs to be hi_HI.json ? (it has no geography based versions)

**Comment by ventoy** [comment]
Should in `xx_YY` format, and also need a txt file in 
https://github.com/ventoy/Ventoy/tree/master/INSTALL/grub/help

**Comment by wiz64** [comment]
done

**Pull request merged**
