### PR TITLE
Update ko_KR.json

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Review by wiz64 — COMMENTED** [review]
...

**Review by wiz64 — CHANGES_REQUESTED** [review]
Please change -> L:한국어 번역:비너스걸
which translated to "Korean Translation:VenusGirl"
- it should be "Language" and not "Korean Translation:VenusGirl"
- Don't put your name here, keep it clean

**Review by wiz64 — CHANGES_REQUESTED** [review]
Please change

**Review by VenusGirl — COMMENTED** [review]
Fixed

**Pull request merged**
