### PR TITLE
Fix grammar for english language

### PR DESCRIPTION
**Pull request by Diacius**
Make a few tweaks so that the English language version is more accurate and flows better.

### CODE REVIEW

**Comment by Diacius** [comment]
@ventoy is it possible to merge this?

**Comment by wiz64** [comment]
🤣 looks like you're writing a journal

**Comment by Diacius** [comment]
what?

**Comment by wiz64** [comment]
> what?

i don't feel that many of the changes are really better.
in > on ..
"STR_VTSI_CREATE_TIP" : we ? or ventoy ?
overall i think current translations are fine, and like they don't really need to be changed.

**Comment by Diacius** [comment]
Fair enough, some of the changes are little pedantic. But I think that my version flows better and does make the messages in the app easier to read, its not like it's loads of effort for me to make these changes, its usually more effort to get the pull request merged!

**Comment by wiz64** [comment]
well, let longpanda decide :-)

**Comment by Diacius** [comment]
I have created a new pull request with updated translations #2803

**Pull request closed without merging**
