### PR TITLE
language.json: Update desciption, Update Tamil translation

### PR DESCRIPTION
**Pull request by kbdharun**
## Changes

- Updated Tamil translation.
- Updated description throughout the page from `Currently Ventoy does not support 4K native device.` to `Currently, Ventoy does not support 4K native devices.`

### CODE REVIEW

**Comment by ventoy** [comment]
Contained in latest commit.

**Comment by kbdharun** [comment]
> Contained in latest commit.

Thanks

**Comment by kbdharun** [comment]
Would a `,` be required after Currently?

**Comment by wiz64** [comment]
> Wouldn't a `,` be required after Currently?
> 
> Here [7035787](https://github.com/ventoy/Ventoy/commit/7035787f387f3d78338fe405c4a66834811169a1)

It sounds really passive...

**Pull request closed without merging**
