### PR TITLE
Update ko_KR.txt

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Review by wiz64 — CHANGES_REQUESTED** [review]
Please keep your name out of 'L' from the help menu and change it.
It currently points to "Korean Translation:VenusGirl"
which is a wrong translation obviously.
It should point to "Select Language" or "Language selection".
This is not a credits section, Keep your name out of Menu files

**Review by VenusGirl — COMMENTED** [review]
translation correction

**Comment by wiz64** [comment]
> translation correction

clear, can be merged.
change in ##2177 as well.

**Review by wiz64 — APPROVED** [review]
ok

**Pull request merged**
